/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.view;

/**
 *
 * @author guiho
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private int idUsuarioLogado;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal(int idUsuarioLogado) {
        initComponents();
        this.idUsuarioLogado = idUsuarioLogado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        menuBarra = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        munuItemCliente = new javax.swing.JMenuItem();
        menuItemSolicitacao = new javax.swing.JMenuItem();
        menuOpcao = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuItemContatos = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 590));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        menuCadastro.setText("Editar/Cadastrar");

        munuItemCliente.setText("Cliente");
        munuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munuItemClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(munuItemCliente);

        menuItemSolicitacao.setText("Solicitação");
        menuItemSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSolicitacaoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemSolicitacao);

        menuBarra.add(menuCadastro);

        menuOpcao.setText("Opções");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuOpcao.add(menuItemSair);

        menuItemContatos.setText("Contatos");
        menuItemContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContatosActionPerformed(evt);
            }
        });
        menuOpcao.add(menuItemContatos);

        menuBarra.add(menuOpcao);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void munuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munuItemClienteActionPerformed
        if (this.idUsuarioLogado == 1) {
            
            FrmMenuCliente telaMenuCliente = new FrmMenuCliente(this.idUsuarioLogado);
            telaMenuCliente.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Acesso Negado!\nApenas o usuário Administrador tem permissão.");
        }
    }//GEN-LAST:event_munuItemClienteActionPerformed

    private void menuItemContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContatosActionPerformed
        FrmContato telaContato = new FrmContato(this.idUsuarioLogado);
        telaContato.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemContatosActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        int confirma = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja sair do sistema?",
                "Confirmação",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (confirma == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSolicitacaoActionPerformed
        FrmMenuSolicitacao menuSolicitacao = new FrmMenuSolicitacao(this.idUsuarioLogado);
        menuSolicitacao.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSolicitacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Cria e exibe o formulário passando um ID padrão para testes */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemContatos;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSolicitacao;
    private javax.swing.JMenu menuOpcao;
    private javax.swing.JMenuItem munuItemCliente;
    // End of variables declaration//GEN-END:variables
}
